### ISSUE TITLE
How to listen for other than Mouse events?

### ISSUE THREAD

**Issue by torsorensen** [xieziyu/ngx-echarts-starter#1]
Hi,

Nice job so far adaptive the echarts js library for angular.

I have two requests I couldn't find info about in your docs, and wanted to hear if this module is supporting those now or in the future. 

A)
I can listen for click events using your (onChartClick) functions and the like.
However, how do I listen for, say, '[pieselectchanged](https://ecomfe.github.io/echarts-doc/public/en/api.html#events.pieselectchanged)', which would be emitted when a user selects or unselects slices of pie charts with the mouse?

B)
And is it possible to trigger echart events programatically, which in the original js library would happen through dispatchAction()?

**Comment by xieziyu** [comment]
@torsorensen 
It seems you've already found the way to handle it.

Add event listener to `echartsInstance`. Get it in `(chartInit)` callback.

**Comment by torsorensen** [comment]
Yes, figured it out. Thanks!

My issue was also related to the fact that my pie chart data series did not have selectedMode on. It is off by default so I also never received my 'pieselectedchanges' events. Switching this mode on worked.

https://ecomfe.github.io/echarts-doc/public/en/option.html#series
